name: genplan
description: "A Flutter project designed to help people generate plans"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  # shared_preferences: ^2.0.0
  firebase_auth: ">=1.2.0 <10.0.0"
  firebase_core: ">=1.15.0 <10.0.0"
  cloud_firestore: ">=1.10.0 <10.0.0"
  share_plus: ">=1.4.0 <11.0.0"
  font_awesome_flutter: ">=1.2.0 <11.0.0"
  material_design_icons_flutter: ">=7.0.0 <8.0.0"
  http: ">=0.14.0 <1.3.0"
  day_night_switcher: ">=0.2.0 <0.3.0"
  provider: ">=6.1.0 <7.0.0"
  firebase_messaging: ">=14.0.1 <20.0.0"

  # Transitive dependencies with latest versions
  collection: ^1.18.0
  http_parser: ^4.0.2
  leak_tracker: ^10.0.5
  material_color_utilities: ^0.11.1
  meta: ^1.15.0
  stack_trace: ^1.11.1
  string_scanner: ^1.2.0
  test_api: ^0.7.2
  vm_service: ^14.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ">=0.14.1 <0.15.0"
  flutter_lints: ^5.0.0

  # Transitive dev dependencies with latest versions
  leak_tracker_flutter_testing: ^3.0.5
  lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: "assets/icon/ios_icon.png"
  remove_alpha_ios: true
  image_path_android: "assets/icon/android_icon.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#84A1F6"
    theme_color: "#84A1F6"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
  android_adaptive_icon:
    foreground_image: "assets/icon/icon.png"
    background_color: "#84A1F6"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
