name: genplan
description: "A Flutter project designed to help people generate plans"

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# This defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ">=1.3.2 <3.0.0"
  firebase_auth: ">=1.3.1 <6.0.0"
  firebase_core: ">=1.6.0 <4.0.0"
  cloud_firestore: ">=4.4.4 <6.0.0"
  share_plus: ">=10.0.0 <11.0.0"
  font_awesome_flutter: ">=8.4.0 <11.0.0"
  material_design_icons_flutter: ">=7.0.7296 <8.0.0"
  http: ">=1.0.2 <2.0.0"
  day_night_switcher: ">=0.1.0+1 <0.3.0"
  provider: ">=4.1.2 <7.0.0"
  firebase_messaging: ">=15.1.3 <16.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ">=0.10.1 <0.15.0"
  flutter_lints: ">=2.0.0 <6.0.0"

# Override transitive dependencies to ensure the latest versions are used
dependency_overrides:
  collection: ^1.19.0
  material_color_utilities: ^0.12.0
  string_scanner: ^1.3.0
  test_api: ^0.7.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: "assets/icon/ios_icon.png"
  remove_alpha_ios: true
  image_path_android: "assets/icon/android_icon.png"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#84A1F6"
    theme_color: "#84A1F6"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"
  android_adaptive_icon:
    foreground_image: "assets/icon/icon.png"
    background_color: "#84A1F6"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/icon.png
