// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8bhTlZ-SgXkqamb8kAdHZyDbZipC3FjI',
    appId: '1:732566389986:web:da45b18001d6f4c0bf4abb',
    messagingSenderId: '732566389986',
    projectId: 'gen-plan',
    authDomain: 'gen-plan.firebaseapp.com',
    storageBucket: 'gen-plan.appspot.com',
    measurementId: 'G-XQ1NDKM369',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtPD8XtBlKJmX3iC_omGoWkP2vBZqb7Fk',
    appId: '1:732566389986:android:6ab4af040e0c2ababf4abb',
    messagingSenderId: '732566389986',
    projectId: 'gen-plan',
    storageBucket: 'gen-plan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjdlNz9X9gD-BDCforQKqxpGX74sYIbEM',
    appId: '1:732566389986:ios:2d1e4a5a568e9227bf4abb',
    messagingSenderId: '732566389986',
    projectId: 'gen-plan',
    storageBucket: 'gen-plan.appspot.com',
    iosBundleId: 'com.example.genPlan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjdlNz9X9gD-BDCforQKqxpGX74sYIbEM',
    appId: '1:732566389986:ios:2d1e4a5a568e9227bf4abb',
    messagingSenderId: '732566389986',
    projectId: 'gen-plan',
    storageBucket: 'gen-plan.appspot.com',
    iosBundleId: 'com.example.genPlan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8bhTlZ-SgXkqamb8kAdHZyDbZipC3FjI',
    appId: '1:732566389986:web:6ee42d3873e09772bf4abb',
    messagingSenderId: '732566389986',
    projectId: 'gen-plan',
    authDomain: 'gen-plan.firebaseapp.com',
    storageBucket: 'gen-plan.appspot.com',
    measurementId: 'G-63LTE6XE2H',
  );
}
